# Generated by Django 4.1.1 on 2022-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=2000)),
                ('main_picture', models.ImageField(upload_to='people')),
            ],
        ),
    ]
