# Generated by Django 4.1.1 on 2022-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='bio',
            field=models.TextField(),
        ),
    ]
